task:
  name: Build Evolution X for RMX3371
  container:
    image: ubuntu:24.04
    cpu: 8
    memory: 32G

  environment:
    CCACHE_DIR: /tmp/ccache
    USE_CCACHE: 1
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci"

  install_script:
    - apt update
    - apt -y upgrade 
    - DEBIAN_FRONTEND=noninteractive apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk git-lfs python-is-python3 wget
    - DEBIAN_FRONTEND=noninteractive apt install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo wget rsync git-lfs openjdk-8-jdk python-is-python3
    - curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
    - chmod a+x /usr/local/bin/repo
    
  all_build_script:
    - mkdir evox
    - cd evox
    - repo init -q --no-repo-verify --depth=1 -u https://github.com/Evolution-X/manifest -b vic --git-lfs
    - repo sync -c --no-clone-bundle --no-tags --force-sync --optimized-fetch --prune -j8
    - git clone -b 6.0 https://github.com/legionos-devices/android_device_realme_rmx3371.git device/realme/rmx3371
    - git clone -b lineage-22.2 https://github.com/legionos-devices/android_vendor_realme_rmx3371.git vendor/realme/rmx3371
    - git clone -b fifteen https://github.com/legionos-devices/android_kernel_realme_sm8250.git kernel/realme/sm8250
    - git clone -b 6.0 https://github.com/legionos-devices/hardware_oplus.git hardware/oplus
    - pwd
    - ls build/make/core/envsetup.mk
    - ls
    - source build/envsetup.sh
    - . build/envsetup.sh
    - lunch lineage_rmx3371-bp1a-user
    - mka evolution -j$(nproc)

  artifacts:
    files:
      - evox/out/target/product/rmx3371/*.zip
      - evox/out/target/product/rmx3371/*.img
